name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Se ejecuta cada vez que haces push a main

  # Permite ejecutar este workflow manualmente desde la pestaña Actions
  workflow_dispatch:

# Configura los permisos del GITHUB_TOKEN para permitir el despliegue en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue en progreso a la vez
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar proyecto (Vite)
        run: npm run build

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Subir artefacto de producción
        uses: actions/upload-pages-artifact@v3
        with:
          # Vite por defecto compila en la carpeta 'dist'
          path: './dist'

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4